### ISSUE TITLE
How to add env variables now?

### ISSUE THREAD

**Issue by deejbee** [coreui/coreui-free-vue-admin-template#100]
I was using the devenv-webpack package with version 1 however I created a new project from scratch using this template and now I can't see a way to use env variables in the ui any more (e.g. MY_API_URL).  Can anyone help?  

Many thanks.

**Comment by xidedix** [comment]
starting with `CoreUI for Vue v2.0.0-beta.5` uses `Vue CLI v3`
please take a look at Vue CLI guide: [Environment Variables](https://cli.vuejs.org/guide/mode-and-env.html)

**Comment by deejbee** [comment]
I totally missed it.  Thanks.  The bit about prefixing with `VUE_APP_` is worth noting.
