### ISSUE TITLE
Request for webpack.config 

### ISSUE THREAD

**Issue by Alirezanet** [coreui/coreui-free-vue-admin-template#107]
Can anyone share the `webpack.config.js` file associated with this template that can be used?

**Comment by xidedix** [comment]
hi @Alirezanet 
Tweaking the Webpack config can be done via the new `vue.config.js` file. If you want to add a Webpack plugin (not to be confused with a Vue CLI plugin), płace your code into the `configureWebpack` property. To see the runtime config, use the command `vue inspect`.

**Comment by Alirezanet** [comment]
@xidedix thank you. finally i found that ...

**Comment by xidedix** [comment]
@Alirezanet  Thanks for the follow-up.
It appears to be solved, closing.
