### ISSUE TITLE
Buttons cursor for "disabled" state is wrong

### ISSUE THREAD

**Issue by KonradDeskiewicz** [coreui/coreui-free-vue-admin-template#108]
Can you move button default cursor to variable to be setup according to taste?
Current obligatory `button { cursor: pointer }` breaks proper button behavior - disabled buttons should not be indicated as clickable. What is well done in bootstrap 4, is broken in CoreUI. 
I respect your approach, and some cases will go fine with this, but this is counter-intuitive especially for "new users". They are not able to distinguish disabled state only from "bleached color", as they are not familiar with color scheme.

**Comment by woothu** [comment]
This issue have been fixed.
