### ISSUE TITLE
Integration with electron

### ISSUE THREAD

**Issue by ortix** [coreui/coreui-free-vue-admin-template#11]
I've been struggling for quite some time to get CoreUI up and running inside electron with the entire toolchain you have provided. I really love the hot pluggable modules and all that magic you have incorporated but that config files are so convoluted that I can't figure out for the life of me how use this system in Electron.

I see that the UI is served through Express and the hot pluggable modules are inserted as middleware into the server. This probably will not work with electron as I need access to internal node modules from within the renderer.

Do you have any idea as to how to go about this?

Thanks!

**Comment by Vincebe** [comment]
up :)

**Comment by woothu** [comment]
We are not planning to integrate coreui with electron.js in near future, but pull request are welcomed :)
