### ISSUE TITLE
｢wdm｣: Failed to compile.

### ISSUE THREAD

**Issue by IzadZ** [coreui/coreui-free-vue-admin-template#110]
I have an issue, i have the pro Vue version and i run npm install using the right node and npm version, when i run "npm run dev" i got this compile error : 

```
 Asset    Size  Chunks  Chunk Names
app.js  296 kB       0  app
   [1] multi ./build/dev-client ./src/main.js 40 bytes {0} [built]
   [2] ./build/dev-client.js 245 bytes {0} [built]
   [3] ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js 852 bytes {0} [built]
   [4] ./node_modules/eventsource-polyfill/dist/eventsource.js 17.7 kB {0} [built]
   [5] (webpack)-hot-middleware/client.js?noInfo=true&reload=true 7.35 kB {0} [built]
   [6] (webpack)/buildin/module.js 517 bytes {0} [built]
   [7] ./node_modules/querystring-es3/index.js 127 bytes {0} [built]
   [9] ./node_modules/querystring-es3/encode.js 2.54 kB {0} [built]
  [10] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
  [11] ./node_modules/ansi-regex/index.js 135 bytes {0} [built]
  [12] (webpack)-hot-middleware/client-overlay.js 2.21 kB {0} [built]
  [13] ./node_modules/ansi-html/index.js 4.26 kB {0} [built]
  [14] ./node_modules/html-entities/index.js 231 bytes {0} [built]
  [17] (webpack)-hot-middleware/process-update.js 4.33 kB {0} [built]
  [18] ./src/main.js 1.01 kB {0} [built] [failed] [1 error]
    + 4 hidden modules

ERROR in ./src/main.js
Module build failed: Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy (/home/izad/Documents/mpec/icare-vue-starter/node_modules/eslint/lib/config.js:256:39)
    at Config.getConfigHierarchy (/home/izad/Documents/mpec/icare-vue-starter/node_modules/eslint/lib/config.js:180:43)
    at Config.getConfigVector (/home/izad/Documents/mpec/icare-vue-starter/node_modules/eslint/lib/config.js:287:21)
    at Config.getConfig (/home/izad/Documents/mpec/icare-vue-starter/node_modules/eslint/lib/config.js:330:29)
    at processText (/home/izad/Documents/mpec/icare-vue-starter/node_modules/eslint/lib/cli-engine.js:162:33)
    at CLIEngine.executeOnText (/home/izad/Documents/mpec/icare-vue-starter/node_modules/eslint/lib/cli-engine.js:618:17)
    at lint (/home/izad/Documents/mpec/icare-vue-starter/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/home/izad/Documents/mpec/icare-vue-starter/node_modules/eslint-loader/index.js:213:21)
 @ multi ./build/dev-client ./src/main.js
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  1.45 MB       0  
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./index.html 1.66 kB {0} [built]
       [1] ./node_modules/lodash/lodash.js 540 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.
Listening at http://localhost:8080
```
I can't find the solution and i need your help.

**Comment by xidedix** [comment]
@IzadZ any details?

**Comment by IzadZ** [comment]
i uptated the post :)

**Comment by xidedix** [comment]
it's possible that ESLint needs configuration on your machine
```bash
./node_modules/.bin/eslint --init
```

**Comment by IzadZ** [comment]
@xidedix  yes this seem to be the issue, do you know a quick start to config ESlint for Vue core pro ?

**Comment by xidedix** [comment]
starting from `2.0.0-beta.5` you can try: 
```bash
vue add @vue/eslint
```

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive or answered above. Please comment and/or reopen if you feel the issue has not been resolved.

**Comment by peerit12** [comment]
I am getting the same issue but showing any error

Hash: 0074b8c8ebf789683027
Time: 168117ms
chunk {app-features-audit-tasks-tasks-module-ngfactory} app-features-audit-tasks-tasks-module-ngfactory.js, app-features-audit-tasks-tasks-module-ngfactory.js.map (app-features-audit-tasks-tasks-module-ngfactory) 138 kB  [rendered]
chunk {common} common.js, common.js.map (common) 3.62 kB  [rendered]
chunk {default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~063c6960} default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~063c6960.js, default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~063c6960.js.map (default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~063c6960) 69 kB  [rendered]
chunk {default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~13ef0a30} default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~13ef0a30.js, default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~13ef0a30.js.map (default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~13ef0a30) 268 kB  [rendered]
chunk {default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~2fbe3e16} default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~2fbe3e16.js, default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~2fbe3e16.js.map (default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~2fbe3e16) 1.11 MB  [rendered]
chunk {default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~fcbe6bd8} default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~fcbe6bd8.js, default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~fcbe6bd8.js.map (default~app-features-audit-tasks-tasks-module-ngfactory~features-administration-administration-modul~fcbe6bd8) 133 kB  [rendered]
chunk {default~features-administration-administration-module-ngfactory~features-audit-visits-visits-module-~35e721c8} default~features-administration-administration-module-ngfactory~features-audit-visits-visits-module-~35e721c8.js, default~features-administration-administration-module-ngfactory~features-audit-visits-visits-module-~35e721c8.js.map (default~features-administration-administration-module-ngfactory~features-audit-visits-visits-module-~35e721c8) 2.11 MB  [rendered]
chunk {default~features-administration-administration-module-ngfactory~features-audit-visits-visits-module-~7f441732} default~features-administration-administration-module-ngfactory~features-audit-visits-visits-module-~7f441732.js, default~features-administration-administration-module-ngfactory~features-audit-visits-visits-module-~7f441732.js.map (default~features-administration-administration-module-ngfactory~features-audit-visits-visits-module-~7f441732) 33.1 kB  [rendered]
chunk {default~features-administration-administration-module-ngfactory~features-entityForms-audit-form-audi~0576ce58} default~features-administration-administration-module-ngfactory~features-entityForms-audit-form-audi~0576ce58.js, default~features-administration-administration-module-ngfactory~features-entityForms-audit-form-audi~0576ce58.js.map (default~features-administration-administration-module-ngfactory~features-entityForms-audit-form-audi~0576ce58) 2.02 MB  [rendered]
chunk {default~features-commandCenter-command-center-command-center-module-ngfactory~features-opportunity-o~f41180d0} default~features-commandCenter-command-center-command-center-module-ngfactory~features-opportunity-o~f41180d0.js, default~features-commandCenter-command-center-command-center-module-ngfactory~features-opportunity-o~f41180d0.js.map (default~features-commandCenter-command-center-command-center-module-ngfactory~features-opportunity-o~f41180d0) 24.8 kB  [rendered]
chunk {default~features-commandCenter-command-center-command-center-module-ngfactory~features-optimize-play~a85eaf34} default~features-commandCenter-command-center-command-center-module-ngfactory~features-optimize-play~a85eaf34.js, default~features-commandCenter-command-center-command-center-module-ngfactory~features-optimize-play~a85eaf34.js.map (default~features-commandCenter-command-center-command-center-module-ngfactory~features-optimize-play~a85eaf34) 77.8 kB  [rendered]
chunk {default~features-optimize-playbook-playbook-module-ngfactory~features-optimize-task-task-module-ngfa~d10c6283} default~features-optimize-playbook-playbook-module-ngfactory~features-optimize-task-task-module-ngfa~d10c6283.js, default~features-optimize-playbook-playbook-module-ngfactory~features-optimize-task-task-module-ngfa~d10c6283.js.map (default~features-optimize-playbook-playbook-module-ngfactory~features-optimize-task-task-module-ngfa~d10c6283) 42.5 kB  [rendered]
chunk {features-administration-administration-module-ngfactory} features-administration-administration-module-ngfactory.js, features-administration-administration-module-ngfactory.js.map (features-administration-administration-module-ngfactory) 730 kB  [rendered]
chunk {features-audit-dashboard-dashboard-module-ngfactory} features-audit-dashboard-dashboard-module-ngfactory.js, features-audit-dashboard-dashboard-module-ngfactory.js.map (features-audit-dashboard-dashboard-module-ngfactory) 151 kB  [rendered]
chunk {features-audit-visits-visits-module-ngfactory} features-audit-visits-visits-module-ngfactory.js, features-audit-visits-visits-module-ngfactory.js.map (features-audit-visits-visits-module-ngfactory) 217 kB  [rendered]
chunk {features-auth-auth-module-ngfactory} features-auth-auth-module-ngfactory.js, features-auth-auth-module-ngfactory.js.map (features-auth-auth-module-ngfactory) 65.7 kB  [rendered]
chunk {features-commandCenter-command-center-command-center-module-ngfactory} features-commandCenter-command-center-command-center-module-ngfactory.js, features-commandCenter-command-center-command-center-module-ngfactory.js.map (features-commandCenter-command-center-command-center-module-ngfactory) 1.94 MB  [rendered]
chunk {features-entityForms-audit-form-audit-form-module-ngfactory} features-entityForms-audit-form-audit-form-module-ngfactory.js, features-entityForms-audit-form-audit-form-module-ngfactory.js.map (features-entityForms-audit-form-audit-form-module-ngfactory) 190 kB  [rendered]
chunk {features-opportunity-opportunity-module-ngfactory} features-opportunity-opportunity-module-ngfactory.js, features-opportunity-opportunity-module-ngfactory.js.map (features-opportunity-opportunity-module-ngfactory) 706 kB  [rendered]
chunk {features-optimize-optimize-module-ngfactory} features-optimize-optimize-module-ngfactory.js, features-optimize-optimize-module-ngfactory.js.map (features-optimize-optimize-module-ngfactory) 125 kB  [rendered]
chunk {features-optimize-playbook-playbook-module-ngfactory} features-optimize-playbook-playbook-module-ngfactory.js, features-optimize-playbook-playbook-module-ngfactory.js.map (features-optimize-playbook-playbook-module-ngfactory) 353 kB  [rendered]
chunk {features-optimize-segment-segment-module-ngfactory} features-optimize-segment-segment-module-ngfactory.js, features-optimize-segment-segment-module-ngfactory.js.map (features-optimize-segment-segment-module-ngfactory) 301 kB  [rendered]
chunk {features-optimize-task-task-module-ngfactory} features-optimize-task-task-module-ngfactory.js, features-optimize-task-task-module-ngfactory.js.map (features-optimize-task-task-module-ngfactory) 164 kB  [rendered]
chunk {main} main.js, main.js.map (main) 1.54 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 235 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 12.2 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 3.67 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 15.9 MB [initial] [rendered]


ℹ ｢wdm｣: Failed to compile.

**Comment by Mediateri** [comment]
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/vagrant/workspace/diveintopost/node_modules
✖ ｢wdm｣: Hash: 3d3a32326b676751d0fb
Version: webpack 4.41.2
Time: 2877ms
Built at: 11/12/2019 1:50:54 PM
  Asset     Size  Chunks             Chunk Names
main.js  365 KiB    main  [emitted]  main
Entrypoint main = main.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./src 40 bytes {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/clients/SockJSClient.js] (webpack)-dev-server/client/clients/SockJSClient.js 3.33 KiB {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.89 KiB {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/utils/getCurrentScriptSource.js] (webpack)-dev-server/client/utils/getCurrentScriptSource.js 658 bytes {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/node_modules/ansi-html/index.js] (webpack)-dev-server/node_modules/ansi-html/index.js 4.16 KiB {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/node_modules/ansi-regex/index.js] (webpack)-dev-server/node_modules/ansi-regex/index.js 135 bytes {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/node_modules/html-entities/index.js] (webpack)-dev-server/node_modules/html-entities/index.js 231 bytes {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
    + 17 hidden modules

ERROR in Entry module not found: Error: Can't resolve './src' in '/home/vagrant/workspace/diveintopost/node_modules'

ERROR in multi (webpack)-dev-server/client?http://localhost:8080 ./src
Module not found: Error: Can't resolve './src' in '/home/vagrant/workspace/diveintopost/node_modules'
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src main[1]
ℹ ｢wdm｣: Failed to compile.

me too i have this issue when i run  webpack-dev-server

**Comment by biancaramalho** [comment]
> ℹ ｢wds｣: Project is running at http://localhost:8080/
> ℹ ｢wds｣: webpack output is served from /
> ℹ ｢wds｣: Content not from webpack is served from /home/vagrant/workspace/diveintopost/node_modules
> ✖ ｢wdm｣: Hash: 3d3a32326b676751d0fb
> Version: webpack 4.41.2
> Time: 2877ms
> Built at: 11/12/2019 1:50:54 PM
> Asset Size Chunks Chunk Names
> main.js 365 KiB main [emitted] main
> Entrypoint main = main.js
> [0] multi (webpack)-dev-server/client?http://localhost:8080 ./src 40 bytes {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/clients/SockJSClient.js] (webpack)-dev-server/client/clients/SockJSClient.js 3.33 KiB {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.89 KiB {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/utils/getCurrentScriptSource.js] (webpack)-dev-server/client/utils/getCurrentScriptSource.js 658 bytes {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/node_modules/ansi-html/index.js] (webpack)-dev-server/node_modules/ansi-html/index.js 4.16 KiB {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/node_modules/ansi-regex/index.js] (webpack)-dev-server/node_modules/ansi-regex/index.js 135 bytes {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/node_modules/html-entities/index.js] (webpack)-dev-server/node_modules/html-entities/index.js 231 bytes {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
> [../../../.nvm/versions/node/v10.16.0/lib/node_modules/webpack/hot sync ^./log$] (webpack)/hot sync nonrecursive ^./log$ 170 bytes {main} [built]
> + 17 hidden modules
> 
> ERROR in Entry module not found: Error: Can't resolve './src' in '/home/vagrant/workspace/diveintopost/node_modules'
> 
> ERROR in multi (webpack)-dev-server/client?http://localhost:8080 ./src
> Module not found: Error: Can't resolve './src' in '/home/vagrant/workspace/diveintopost/node_modules'
> @ multi (webpack)-dev-server/client?http://localhost:8080 ./src main[1]
> ℹ ｢wdm｣: Failed to compile.
> 
> me too i have this issue when i run webpack-dev-server

I solved it replacing "webpack-dev-server" to "webpack server" in package.json file. In scripts part.
