### ISSUE TITLE
remove duplicate favicon

### ISSUE THREAD

**Issue by mariusa** [coreui/coreui-free-vue-admin-template#112]
There are 2 favicons now:

https://github.com/coreui/coreui-free-vue-admin-template/blob/master/public/favicon.ico

https://github.com/coreui/coreui-free-vue-admin-template/blob/master/public/img/favicon.png

Please remove the 1st, leaving only the png, similar to the rest of the logos.
Update this in index.html:
```
<link rel="icon" href="<%= BASE_URL %>img/favicon.png">
```

Thanks!

**Comment by woothu** [comment]
Resolved with https://github.com/coreui/coreui-free-vue-admin-template/commit/aafa8c88c7a39beaeaf7c89f3d2e1f7f3294b653
