### ISSUE TITLE
this.$router in component

### ISSUE THREAD

**Issue by bosemian** [coreui/coreui-free-vue-admin-template#114]
I have a problem to navigate route my web via event handler such as @click

![image](https://user-images.githubusercontent.com/22653043/43258298-89c27f12-90fc-11e8-9f30-74c8305e4df3.png)

Can i use a this.$router in a component ?

**Comment by SamiUrias** [comment]
Yes, you can use the router in a component, but I think that you are not doing it right.
Don't put that into the console.log ...
