### ISSUE TITLE
Unit test failing

### ISSUE THREAD

**Issue by amandiobm** [coreui/coreui-free-vue-admin-template#115]
Hello guys, I just clone the repository and run all the tests, and I received this error.

> @coreui/coreui-free-vue-admin-template@2.0.0-beta.7 test:unit 
> vue-cli-service test:unit

 FAIL  tests/unit/Dashboard.spec.js
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.49s
Ran all test suites.
---

I have an old version `beta-5`, with an old lock file which run perfectly.

My setup is:
Linux Ubuntu 16.04 LTS
NPM: 6.2.0
NODE: 8.11.3

Can someone help?!

**Comment by xidedix** [comment]
see also: https://stackoverflow.com/questions/51554366/npm-test-fail-with-jest/51554619

**Comment by xidedix** [comment]
looks like it was introduced with `vue-cli ^3.0.0-rc.6`

add this to your `jest.config.js`
```js
module.exports = {
  verbose: true,
  testURL: "http://localhost/",
  ...
}
```

**Comment by amandiobm** [comment]
Hey @xidedix, Tks for the commented. I fixed on that same day. But was in a hurry, that I forget to thank you. So... Tks ;))
