### ISSUE TITLE
Breadcrumb not supporting params routes

### ISSUE THREAD

**Issue by guilhermeaiolfi** [coreui/coreui-free-vue-admin-template#121]
Hi,

It shows, for example, /user/:id instead of /user/1. I guess it's a ```vue-bootstrap``` since it uses its component directly. ```coreui``` v1 was OK.

I'll take a look later and see if I can solve the problem.

**Comment by Augustoz1** [comment]
You have to copy the original component from @coreui/vue/src/components/Breadcrumb/Breadcrumb.vue and replace: 
`<router-link :to="routeObject" v-else>{{ getName(routeObject) }}</router-link>`
with
`<router-link :to="{name:routeObject.name}" v-else>{{ getName(routeObject) }}</router-link>`

[Related](https://github.com/vuejs/vue-router/issues/1435)

**Comment by HakanL** [comment]
I have CoreUI Pro and I'm also running into this problem, but I don't understand the workaround above, where can I find `Breadcrumb.vue`?
