### ISSUE TITLE
Option to hide items in _nav.js

### ISSUE THREAD

**Issue by Alifar** [coreui/coreui-free-vue-admin-template#143]
Is there a way or option to hide items in the sidebar menu?

```
{
    name: 'Hide this item',
    url: '/url',
    icon: 'icon-tag'
},
```

**Comment by woothu** [comment]
You can just comment, delete or modify items. Notice that links would be still available - you can modify them in src/router/index.js.

**Comment by Alifar** [comment]
Thank you for your reply, but isn’t there a method to hide an item with a boolean?

**Comment by woothu** [comment]
We are working to add a parameter which will be used for adding html attributes, so there will probably be such opportunity in the near future.

**Comment by Alifar** [comment]
> We are working to add a parameter which will be used for adding html attributes, so there will probably be such opportunity in the near future.

Where can I add such a parameters? 

Thank you.

**Comment by woothu** [comment]
This feature is not yet available.

**Comment by omer2500** [comment]
maybe this will help,
i also encountered this issue when need to show and hide menu items that only admin should see,
i eventually made 2 files, one is the regular _nav.js file and one is _navAdmin.js
and on the sidebar component i'm putting both of them into computed property which checks the user type and return array according to that check.
