### ISSUE TITLE
File to import not found or unreadable: node_modules/bootstrap/scss/functions

### ISSUE THREAD

**Issue by ijunaid8989** [coreui/coreui-free-vue-admin-template#146]
In reference to

https://github.com/coreui/coreui-free-react-admin-template/issues/116#issuecomment-447027409
https://github.com/coreui/coreui-free-angular-admin-template/issues/105

The same issue is coming in VueJS theme as well.

I am following the whole package.json file but it's giving me the same error on load. 

![image](https://user-images.githubusercontent.com/13561999/50570945-05478a80-0dbf-11e9-8a9e-b46cdd9a5bef.png)

**Comment by xidedix** [comment]
Starting with `@coreui/coreui v2.0.4` and up there is no need for an explicit import of bootstrap variables and functions into the template  
The current version of `src/assets/scss/vendors/_variables.scss` should look like this:
```scss
// Override Boostrap variables
@import "../variables";
@import "~bootstrap/scss/mixins";
@import "~@coreui/coreui/scss/variables";
```
