### ISSUE TITLE
How to pass input/button component in c-table ? 

### ISSUE THREAD

**Issue by Enigma10** [coreui/coreui-free-vue-admin-template#148]
Button is not rendering inside table.
`<c-table :table-data="items" :fields="fields" caption="<i class='fa fa-align-justify'></i> Simple Table">
  <template slot="actions" slot-scope="cell">
    <b-button>One</b-button>
  </template>
</c-table>`

**Comment by woothu** [comment]
In the current version, c-table is only used as a wrapper component and is not fully adjustable. If you want to manipulate the content you should use bootstrap-vue b-table component (which is used in c-table) or wait for next version in which we will have our own table component :)
