### ISSUE TITLE
SidebarToggler shouldn't be required twice

### ISSUE THREAD

**Issue by fancydev18** [coreui/coreui-free-vue-admin-template#154]
We'd like to remove this line, in order to have desktop view always show the sidebar, without any toggle menu:

https://github.com/coreui/coreui-free-vue-admin-template/blob/8fee20b35d9f5f4838702f7b80bda438cd580165/src/containers/DefaultContainer.vue#L9

However, if that's removed, the sidebar will disappear after a click on one of the items.
Expected: Sidebar should disappear after click only when mobile is true AND only for displays <= display property (as set on line 4).

**Comment by woothu** [comment]
Thank you for reporting this issue. Currently, we are improving the sidebar, it will gain rework in version 3.0.

For now, the easiest solution for your case is to change class="d-md-down-none" to class="d-none" in line 9.  You can also change breakpoints to 'sm' in both lines 4 and 9 to have the mobile view only on small screens.
