### ISSUE TITLE
Is it possible to make sidebar hidden by default? 

### ISSUE THREAD

**Issue by nur8sultan** [coreui/coreui-free-vue-admin-template#156]
I know that its possible to make it minimized by default by adding classes to body

**Comment by xidedix** [comment]
@nur8sultan 

in `src/containers/DefaultContainer.vue` 
add `:defaultOpen=false` to `SidebarToggler` like this:

```html
<SidebarToggler class="d-md-down-none" display="lg" :defaultOpen=false />
```
