### ISSUE TITLE
How can I Change language of Core UI components ? Is there any method to convert Language in Core UI? 

### ISSUE THREAD

**Issue by prkhrv** [coreui/coreui-free-vue-admin-template#162]
Any Way to do that will help?

**Comment by woothu** [comment]
Hi! 
Implementation of internalization could be diverse - backend, as well as frontend solutions can be used so it is not template responsibility to handle this feature.

If you are interested in internalization in Vue here is an article, which may interest you:
https://medium.com/hypefactors/add-i18n-and-manage-translations-of-a-vue-js-powered-website-73b4511ca69c
