### ISSUE TITLE
navbar-brand width is set to 155px vs 200px

### ISSUE THREAD

**Issue by fancydev18** [coreui/coreui-free-vue-admin-template#165]
Hi,

Following up on https://github.com/coreui/coreui-free-vue-admin-template/issues/154

When setting SidebarToggler to 'd-none', other items in header move to the left -- see attached. 'Dashboard' is no longer aligned with sidebar.
navbar-brand width is set to 155px vs 200px, to be same as the sidebar. Can't find how to overwrite this. If using !important, it breaks the mobile view.

We believe navbar-brand should be same as the sidebar (200px) and items inside it (img) centered.

Also, would be great if by default there would be no SidebarToggler in desktop-view. We already have the minify toggler in sidebar. There's no need to add more togglers just because it's possible.

Thanks

![Screenshot from 2019-08-08 12-48-40](https://user-images.githubusercontent.com/45625044/62693576-772e2500-b9db-11e9-951a-65e722c9dcc2.png)

**Comment by woothu** [comment]
Hi! sidebar toggler on desktop view is a default feature of the CoreUI template. By default we don't have toggler inside the sidebar, so the header toggler is necessary. You can just delete it and wrap brand and mobile toggler in div with min-width.

In DefaultContainer.vue:
```
<AppHeader fixed>
   <div style="min-width:200px;">
    <SidebarToggler class="d-lg-none" display="md" mobile />
       <b-link class="navbar-brand" to="#">
          <img class="navbar-brand-full" src="img/brand/logo.svg" width="89" height="25" alt="CoreUI Logo">
          <img class="navbar-brand-minimized" src="img/brand/sygnet.svg" width="30" height="30" alt="CoreUI Logo">
      </b-link>
   </div>

```

**Comment by fancydev18** [comment]
Hi, thanks for your help!

That solution doesn't work properly on mobile: sidebar toogle will take 200px instead of the small space it needs.

It would be great to have this fixed in coreui, somehow.

There's a toggler inside sidebar on desktop, which leaves only the icons. If you could measure the usage or ask users about the desktop toggler, I'm sure it's not that used. It could be left in code commented out.

The patters is visible on all sites navigation: on desktop they just show the menu, on mobile most have a menu toggler. NO site has a menu toggler on desktop, because it's not needed.

**Comment by woothu** [comment]
Thank you for your suggestions, we will consider it.

Did you wrap Toggler AND link with the brand in the div with min-width? It should work on mobile.

**Comment by woothu** [comment]
Thank you for your suggestions, we will consider it.

I just checked for possible solutions and code below works fine both on desktop and mobile, both with commented or not commented toggler in 2.1.5 version.  

```
<b-link class="navbar-brand" to="#" style="width:200px">
        <img class="navbar-brand-full" src="img/brand/logo.svg" width="89" height="25" alt="CoreUI Logo">
        <img class="navbar-brand-minimized" src="img/brand/sygnet.svg" width="30" height="30" alt="CoreUI Logo">
</b-link>
<!-- <SidebarToggler class="d-none" display="lg" :defaultOpen=true /> -->
```

**Comment by woothu** [comment]
Thank you for your suggestions, we will consider it.

Now I think I see your problem. You are not talking about mobile view problem, but rather a problem with minimizing on desktop view. You can fix it this way:

 ```
<SidebarToggler class="d-md-down-none invisible"/>
```

We will also rethink the positioning, so it could be easier customed by users :)

**Comment by fancydev18** [comment]
Thank you!
