### ISSUE TITLE
is jQuery required?

### ISSUE THREAD

**Issue by hkchakladar** [coreui/coreui-free-vue-admin-template#166]
Does CoreUI uses jquery?

I got these npm warn
```
npm WARN @coreui/coreui@2.1.12 requires a peer of jquery@1.9.1 - 3 but none is installed. 
You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. 
You must install peer dependencies yourself.
```

Should I install `jQuery` seperately?

**Comment by woothu** [comment]
No, jQuery is not required.

**Comment by hkchakladar** [comment]
So this warning should have been removed.

**Comment by xidedix** [comment]
@hkchakladar 
`@coreui/coreui` is a shared library for the CoreUI ecosystem: static, ajax, vue, react, angular. jQuery is required by static and ajax versions only.
