### ISSUE TITLE
Please let us use any icon system in _nav.js

### ISSUE THREAD

**Issue by mariusa** [coreui/coreui-free-vue-admin-template#167]
Icon systems use various conventions, not just ```<i class='...'></i>```

For example, https://ionicons.com uses
```
<ion-icon name="speedometer"></ion-icon>
```

http://google.github.io/material-design-icons/ uses
```
<i class="material-icons">face</i>
```

Since there's no web standard, please let us specify directly icon like this in _nav.js, instead of requiring the class and forcing the `<i>` system.

Thanks!

**Comment by woothu** [comment]
Hello, 

We are planning to introduce fully customizable nav items generator in version 3. 
Nav items would render through CRenderFunction component:
https://github.com/coreui/coreui-vue/blob/dev/src/components/RenderFunction/CRenderFunction.vue

which enables full vue render function functionality. You can check out this concept on dev branch of new version:
https://github.com/coreui/coreui-free-vue-admin-template/blob/dev/src/containers/TheSidebar.vue
https://github.com/coreui/coreui-free-vue-admin-template/blob/dev/src/containers/_nav.js


For now, you can resign from using _nav.js array and use normal components generation through vue template, or rewrite use CRenderFunction component (alpha) and rewrite _nav.js
