### ISSUE TITLE
Core UI Vue Admin does not render on Weex (Vue Web/Mobile toolkit)

### ISSUE THREAD

**Issue by donwilly2010** [coreui/coreui-free-vue-admin-template#171]
Core UI is so good that I rate it to be the best GUI template.
However, there is a platform for for VueJs called Weex. Weex enables the use of same Vuejs code base for both Web and Mobile development.

This is why most Vuejs developers are not migrating to Weex. Unfortunately, CoreUI Vue Admin does not render on Weex.

This is currently a major problem for most developers who used CoreUi Vue Admin as they will have to dump CoreUi Vue and rewrite their code from start using WeexUi.

Please this needs urgent attention. Please we really need the CoreUI Weex Admin Template.

**Comment by donwilly2010** [comment]
The GUI of current version of CoreUi Vue Admin was totally distorted and non functional when rendered on Weex Toolkit.

Please let us know If or When CoreUI Vue Admin Template version for Weex Toolkit can be available.
 A whole lot of project engineering decisions are based on this.

**Comment by woothu** [comment]
For now, we are busy working on version 3 of CoreUI, so we wouldn't consider implementing this in the near future.
