### ISSUE TITLE
jQuery Dependant?

### ISSUE THREAD

**Issue by AngelinCalu** [coreui/coreui-free-vue-admin-template#174]
If this is supposed to be a `VueJs` template why is jQuery still a requirement?

**Comment by xidedix** [comment]
Hi @AngelinCalu 

jQuery is not required.
The warning comes from `@coreui/coreui` - it works as a shared library for the CoreUI ecosystem: static, ajax, vue, react, and angular. jQuery is required by static and ajax versions only. Incoming CoreUI v3 drops this requirement completely.
