### ISSUE TITLE
npm issues with initial install

### ISSUE THREAD

**Issue by BrettBailey** [coreui/coreui-free-vue-admin-template#176]
Hi

Just downloaded the free template and having followed the instructions I get this as the result to npm install:

found 946 vulnerabilities (65 low, 880 high, 1 critical) in 44508 scanned packages
  run `npm audit fix` to fix 874 of them.
  1 vulnerability requires semver-major dependency updates.
  71 vulnerabilities require manual review. See the full report for details.

The site seems to work but with all those vulnerabilities I'm wondering if this is safe to use?

I'm assuming this also effects the pro-version

~Brett

**Comment by woothu** [comment]
Hi! 

Thank you for your report! In the new version vulnerabilities have been fixed.

Regards
