### ISSUE TITLE
Error: "Loading CSS chunk chunk-05dc8002 failed

### ISSUE THREAD

**Issue by PowerGit** [coreui/coreui-free-vue-admin-template#179]
![image](https://user-images.githubusercontent.com/9403660/67097825-83114100-f1ed-11e9-8f02-2310aad70d39.png)
after `npm run build`
when browser visit the root, it happens. thanks for answer.

**Comment by xidedix** [comment]
Hi @PowerGit 
The information provided is insufficient to investigate the issue.

Does it work with `npm start`?

What's your version of:
- node,
- npm, 
- vue, 
- vue cli,
- browser,
- os

What's in your `package.json` dependencies?

**Comment by PowerGit** [comment]
> Hi @PowerGit
> The information provided is insufficient to investigate the issue.
> 
> Does it work with `npm start`?
> 
> What's your version of:
> 
> * node,
> * npm,
> * vue,
> * vue cli,
> * browser,
> * os
> 
> What's in your `package.json` dependencies?

thank your reply!
i use the origin project, directly run `npm run build`, and put it on my nginx server,
and the nginx.conf is
`location / {
    root coreui/dist/;
}`
which point to the `dist` dir

**Comment by xidedix** [comment]
@PowerGit 

see: https://github.com/coreui/coreui-free-react-admin-template/issues/124#issuecomment-460113218
it might be helpful

**Comment by PowerGit** [comment]
@xidedix 
thank your reply.
i have read the issue and change my nginx.conf, but it seem's to be not the same problem with me, same thing happend.
when i change to use chrome , it got another wrong.
![image](https://user-images.githubusercontent.com/9403660/67136826-c1931400-f25e-11e9-9cf0-cd1b5d7a6cd3.png)

**Comment by PowerGit** [comment]
@xidedix 
finally. Its my fault. thanks your help !
my nginx.conf lack of some item.

`include minm.types;
default_type  application/octet-stream;`

its needed to transfer css and ext. file.
