### ISSUE TITLE
Dynamic tabs + tabs-end slot - upgrade bootstrap-vue from 2.0.0-rc.24 to 2.0.4

### ISSUE THREAD

**Issue by greeven** [coreui/coreui-free-vue-admin-template#180]
I found a certain functionality not working based on the [bootstrap-vue documentation](https://bootstrap-vue.js.org/).

The functionality in question is [Dynamic tabs + tabs-end slot](https://bootstrap-vue.js.org/docs/components/tabs/#dynamic-tabs--tabs-end-slot).

Upgrading from `"bootstrap-vue": "2.0.0-rc.24",` to `"bootstrap-vue": "2.0.4",` in the package.json file did the trick.

I am not sure if this eventually will break something else. Just wanted to let you guys know about it and maybe prevent a headache for others who encounter that problem.

**Comment by woothu** [comment]
Hi, thank you for reporting this issue!

We are planning to release an update with current bootstrap-vue version and needed fixes, stay tuned :)
