### ISSUE TITLE
Cannot find module '@babel/plugin-syntax-top-level-await'

### ISSUE THREAD

**Issue by janhaa** [coreui/coreui-free-vue-admin-template#181]
Above error when running `npm run serve`.

Fixed by `npm install --save-dev @babel/plugin-syntax-top-level-await`

**Comment by woothu** [comment]
Which version?

**Comment by janhaa** [comment]
Hmm, I wasn't able to reproduce now for some reason. Possibly there was something going wrong in my initial install.

**Comment by janhaa** [comment]
Nevermind, was able to reproduce now!

So what seems to be the issue is when renaming the directory. No idea why. Logs attached below:

https://gist.github.com/janhaa/999f671a17fc97a5b6e5a30b18bed3b1

**Comment by woothu** [comment]
I cannot reproduce it even after changing name of the folder and deleting node_modules and package-lock.json
