### ISSUE TITLE
Advanced Datatable localisation issues

### ISSUE THREAD

**Issue by alhemicar** [coreui/coreui-free-vue-admin-template#182]
Hey, is there any way we can get custom messages for datatables? I want to change placeholder for search filter, empty table text and items per page labels to my native language but it's hardcoded and can't take additional input from me. Can you at least make it so that it takes a param where the custom text can be inputed?

**Comment by woothu** [comment]
Customizations you want to make are possible though slots.

https://coreui.io/vue/docs/components/table.html

**Comment by alhemicar** [comment]
I saw that there is a mention of slots, but no any kind of example. Can you perhaps show me an example of a change, let's say how to change main table filter or empty results on the CDataTable component? Sorry to bother, but it's really confusing.

**Comment by woothu** [comment]
You don't change it, you create your own in over-table slot, and no-items-view slot
```js
<CDataTable ...>
  <slot #over-table>
    (Your custom table filter and pagination select)
  </slot>
</CDataTable>
```

**Comment by alhemicar** [comment]
Working like a charm! Thanks for the example!
