### ISSUE TITLE
Module not found in pro

### ISSUE THREAD

**Issue by crabvn** [coreui/coreui-free-vue-admin-template#183]
Hi, I am using version pro": "3.0.0-beta.3

I am trying to change the default to dark but when I uncomment the `scss/themes/dark/coreui-dark` the watcher is saying that the module not found. I checked in the npm_modules the themes/dark folder doesn't have file *coreui-dark*

Please help

**Comment by woothu** [comment]
https://github.com/coreui/coreui-vue/issues/44
