### ISSUE TITLE
Typescript samples

### ISSUE THREAD

**Issue by novecento** [coreui/coreui-free-vue-admin-template#189]
sorry guys, are you planning to insert typescript sample implementations?

**Comment by woothu** [comment]
Typescript starter template is a PRO version feature (it will available probably next week)

**Comment by novecento** [comment]
> Typescript starter template is a PRO version feature (it will available probably next week)

good, let me know :-)

**Comment by woothu** [comment]
Typescript starter is now available for download (for PRO users)
