### ISSUE TITLE
Unused alert3

### ISSUE THREAD

**Issue by ganjarsetia** [coreui/coreui-free-vue-admin-template#190]
May I know what is `alert3` used for?

https://github.com/coreui/coreui-free-vue-admin-template/blob/b8636c729f94e5f76d752166f006e5fbfa95dadd/src/views/notifications/Alerts.vue#L191

I don't see any data use `alert3`.
I can submit PR for remove it and improve the unit test coverage.

**Comment by woothu** [comment]
Hi, thank you for this report!

In fact, it is unnecessary after the third alert deletion. I have fixed it now with f0533a9b2e467d7ed9bcecfd0ca37fc4478b81d8

If you want to advance unit tests PR's are welcomed (please request on 'dev' branch). You can also update vue-test-utils to 1.0.0-beta.31 version.

**Comment by ganjarsetia** [comment]
Sure got it.
