### ISSUE TITLE
Error in render: "Error: info is not a valid hex color"  found in  ---> <MainChartExample> at src/views/charts/MainChartExample.vue        <Dashboard> at src/views/Dashboard.vue          <TheContainer> at src/containers/TheContainer.vue            <App> at src/App.vue              <Root>

### ISSUE THREAD

**Issue by TolrenFrank** [coreui/coreui-free-vue-admin-template#195]
Error in render: "Error: info is not a valid hex color"

found in

---> <MainChartExample> at src/views/charts/MainChartExample.vue
       <Dashboard> at src/views/Dashboard.vue
         <TheContainer> at src/containers/TheContainer.vue
           <App> at src/App.vue
             <Root>

#

**Comment by woothu** [comment]
One of two reasons might ge possible:
- Your browser doesn't support css vars,
- '--info' var is not defined

Either we have wrong support for getting these colors, so thank you for the report.

For a quick fix in MainChartExample.vue line 24:
```js
      const brandSuccess = '#4dbd74'
      const brandInfo = '#20a8d8'
      const brandDanger = '#f86c6b'
```

**Comment by TopCoder1119** [comment]
> Error in render: "Error: info is not a valid hex color"
> 
> found in
> 
> ---> at src/views/charts/MainChartExample.vue
> at src/views/Dashboard.vue
> at src/containers/TheContainer.vue
> at src/App.vue

Can  we connect via skype ?
My skype is  WEBMASTER1120 and I am your senior students on 852 university.
I am glad to see you here. hope we can connect via skype soon if you see this.

**Comment by woothu** [comment]
@TopCoder1119 The same solution can be applied to your case.
