### ISSUE TITLE
columnFilter or tableFilter -> ='{ external: true, lazy: true }'

### ISSUE THREAD

**Issue by peter81git** [coreui/coreui-free-vue-admin-template#196]
I got "Expected Boolean, String, got Object" when setting prop columnFilter or tableFilter to ='{ external: true, lazy: true }' as written in the documentation. Even with this error events are triggered.
The goal is to use external function to filter data, but looking into CDataTable implementation it seems that the only way is to use a template slot for each column.

I'm using vue-free-admin-template that is still beta 4 version, and the docs are updated to beta 11.

**Comment by woothu** [comment]
This depends on coreui-vue library version, try update coreui-vue to beta.11

**Comment by peter81git** [comment]
I've run npm upgrade and now i'm using "@coreui/vue": "^3.0.0-beta.11". It seems ok.
