### ISSUE TITLE
Dashboard visual margin top

### ISSUE THREAD

**Issue by peter81git** [coreui/coreui-free-vue-admin-template#197]
After upgrade to beta 11 version the template dashboard has no margin between header and the first component to be in the container.

![AfterUpdate](https://user-images.githubusercontent.com/44998875/74553001-54626780-4f4e-11ea-8299-a9c0cb2c000a.png)
![BeforeUpdate](https://user-images.githubusercontent.com/44998875/74553003-54fafe00-4f4e-11ea-9a38-0574294d99e4.png)

Best Regards

**Comment by peter81git** [comment]
Seems related to padding-top in "TheContainer".
![Diference](https://user-images.githubusercontent.com/44998875/74554915-81187e00-4f52-11ea-9a67-5b9254e4b025.png)

**Comment by woothu** [comment]
For fix add class 'c-fixed-components' to 'c-wrapper' in TheContainer.vue

**Comment by peter81git** [comment]
Thanks.
