### ISSUE TITLE
Breadcrumbs not working

### ISSUE THREAD

**Issue by fearrr** [coreui/coreui-free-vue-admin-template#2]
Breadcrumbs component not work with vue router, click does not transferring to path.

**Comment by joefresco** [comment]
I concur.  _Home_ is always the current router path for one-level navigation

**Comment by joefresco** [comment]
I submitted a PR to fix the breadcrumb 'Home' issue.  I only have one level of breadcrumbs so this was all that I needed to fix.
https://github.com/mrholek/CoreUI-Vue/pull/17

**Comment by joefresco** [comment]
This could also be related.
https://github.com/vue-bulma/breadcrumb/issues/3

**Comment by xidedix** [comment]
see also vue-bulma/breadcrumb#4

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive or answered above. Please comment and/or reopen if you feel the issue has not been resolved.
