### ISSUE TITLE
Sidebar logo is gone after upgrading from 3.0 beta to final

### ISSUE THREAD

**Issue by mariusa** [coreui/coreui-free-vue-admin-template#202]
Hi,

This used to work in 3.0 beta:
```
<CSidebarBrand 
      :imgFull="{ width: 118, height: 46, alt: 'Logo', src: 'img/brand/coreui-base-white.svg'}"
      :imgMinimized="{ width: 118, height: 46, alt: 'Logo', src: 'img/brand/coreui-signet-white.svg'}"
      :wrappedInLink="{ href: 'https://coreui.io/', target: '_blank'}"
    />
```

3.0 final has these removed, but there's no hint on how to specify the 2 images version.

The only reference I've found is this
https://github.com/coreui/coreui-vue/blob/bdb4b643ca01b474be8a78c2e47c77c877f0cb74/src/components/index.d.ts
but it doesn't work anymore.

How to get the same functionality as in 3.0 beta now?

Thanks

**Comment by woothu** [comment]
Hi!
The component has a breaking change in the library 3.0.0-beta.11 release: https://github.com/coreui/coreui-vue/releases/tag/3.0.0-beta.11.

Now it's just wrapper component, and logo has to be passed inside in default slot, like in https://github.com/coreui/coreui-free-vue-admin-template/blob/master/src/containers/TheSidebar.vue

Btw. thank you for this report, typings are wrong

**Comment by woothu** [comment]
If you want the same functionality use two img's inside with classes "c-sidebar-brand-full" and "c-sidebar-brand-minimized"
