### ISSUE TITLE
Scrollbar not being styled

### ISSUE THREAD

**Issue by va-prans** [coreui/coreui-free-vue-admin-template#203]
so the sidebar scrollbar gets styled whilst the main scrollbar remains unstyled. 

![image](https://user-images.githubusercontent.com/21257070/77422329-8ed0e700-6dcd-11ea-986d-42c1404b7565.png)

vs 

![image](https://user-images.githubusercontent.com/21257070/77422378-a60fd480-6dcd-11ea-9702-b756b33fca4e.png)

this is super weird because sometimes it works and sometimes it doesn't? i was working with the template yesterday and the scrollbar was styled however today it's back at default? (note this is both on the demo site and my own project!)

**Comment by woothu** [comment]
This is the default behavior of all CoreUI templates. Why you find this weird?

**Comment by va-prans** [comment]
> This is the default behavior of all CoreUI templates. Why you find this weird?
> 
> i.e. Facebook use similar styling ;)

hmm.. if you say that the desktop above is the default behaviour then i think i might have bamboozled myself somehow. Because sometimes the scrollbar looks like this.. 

![image](https://user-images.githubusercontent.com/21257070/77428789-f5a7cd80-6dd8-11ea-85f3-9ab58a019dd5.png) 

where it is only active while scrolling (mobile behavior?). i think the "responsive" screen resizer in the chrome dev tools is the culprit.. switching between "responsive" to desktop can sometimes cause the scrollbar to inherit mobile behaviors and style. Meaning that this is an issue with chrome and not coreUI.

i will close this issue and thanks for the hasty reply :)
