### ISSUE TITLE
The design of the login screen is broken when viewed in Edge.

### ISSUE THREAD

**Issue by himeyon** [coreui/coreui-free-vue-admin-template#204]
https://coreui.io/vue/demo/3.0.0/#/pages/login

![image](https://user-images.githubusercontent.com/4468822/77622467-a9e45800-6f81-11ea-9e52-e67ae23f0acd.png)

- Operating system and version
Windows 10
Microsoft Edge 44.17763.831.0

**Comment by woothu** [comment]
This seems edgy :D Thank you for the report (chrome worked fine)

**Comment by woothu** [comment]
fixed in 3.1.0 version
