### ISSUE TITLE
when I navigate from one page to another, the page doesn't scroll to top

### ISSUE THREAD

**Issue by bCliks** [coreui/coreui-free-vue-admin-template#206]
You can reproduce this issue in demo itself.
1. open a page, then scroll till end.
2. now navigate to another page. the new page doesn't scroll to top. it is also in end of the page. 

```
  "@coreui/coreui": "3.0.0",
   "@coreui/vue": "3.0.4",
```

working fine in 3.0.0 beta version.

**Comment by woothu** [comment]
This bug is fixed in `@coreui/coreui` 3.2.0 version
