### ISSUE TITLE
Can not get core ui pro

### ISSUE THREAD

**Issue by rahultrivedi180** [coreui/coreui-free-vue-admin-template#211]
![Screenshot from 2020-04-20 13-02-06](https://user-images.githubusercontent.com/32861078/79725671-32e37a80-8307-11ea-9212-603aae1258c3.png)

Clicking on Get CoreUI PRO is not working. Check your website code and fix this ga not defined issue.

**Comment by woothu** [comment]
Thank you for the report. For hotfix clean site cookies.

**Comment by rahultrivedi180** [comment]
Still not working

**Comment by woothu** [comment]
Which browser do you use?

**Comment by rahultrivedi180** [comment]
> Which browser do you use?

chrome. Latest
