### ISSUE TITLE
async functions not working

### ISSUE THREAD

**Issue by rahultrivedi180** [coreui/coreui-free-vue-admin-template#212]
![Screenshot from 2020-04-23 18-33-10](https://user-images.githubusercontent.com/32861078/80102822-f4f98700-8590-11ea-804a-ba0be4b8c651.png)

**Comment by woothu** [comment]
Hi! Please try adding:
`import 'regenerator-runtime/runtime';`
in main.js

**Comment by rahultrivedi180** [comment]
> Hi! Please try adding:
> `import 'regenerator-runtime/runtime';`
> in main.js

Thanks! It worked
