### ISSUE TITLE
Draggable card position not restored precisely.

### ISSUE THREAD

**Issue by hifall** [coreui/coreui-free-vue-admin-template#214]
Go to:

https://coreui.io/vue/demo/3.0.0/#/plugins/draggable

Click the "Save grid structure to local storage" button.
Then move Card 2 below Card 1.
Click the "Restore layout saved in local storage" button.

The restoration works somewhat: it moves Card 2 around, but not to the original position.

**Comment by woothu** [comment]
Thank you for the report! Issue fixed in 3.1.0 version: https://coreui.io/vue/demo/3.1.0/#/plugins/draggable
