### ISSUE TITLE
Add gradient to charts.

### ISSUE THREAD

**Issue by hifall** [coreui/coreui-free-vue-admin-template#216]
Adding gradient to charts would add a touch of 'modernness' to the already great looking charts.

See here: [https://blog.vanila.io/chart-js-tutorial-how-to-make-gradient-line-chart-af145e5c92f9](https://blog.vanila.io/chart-js-tutorial-how-to-make-gradient-line-chart-af145e5c92f9)

**Comment by woothu** [comment]
Thank you for the idea, we will consider it! 

BTW. It is doable already because we expose Chart.js API in our components. Also, widgets have a gradient background already in the PRO version.
