### ISSUE TITLE
CSelect component binding object instead of value

### ISSUE THREAD

**Issue by miedzwin** [coreui/coreui-free-vue-admin-template#217]
Hi,
I probably found a bug in CSelect component. While passing to options array of objects like in this example: https://coreui.io/vue/docs/components/form-components.html#cselect-api it fails to binding value when object value is 0 or false.
Here is example code:
```
<template>
    <div>
        <CSelect
         :value.sync="selectedValue"
          label="Year"
         :options="[{value: 0, label: 'zero'}, {value: false, label: 'false'}, {value: 1, label: 'one'}]"
        />
    </div>
</template>
<script>
export default {
  data() {
    return {
        selectedValue: null
    }
  }
}
```

Here is value of 'selectedValue' based on selected option:
'zero' selected -> {value: 0, label: 'zero'}
'false' selected -> {value: false, label: 'false'}
'one' selected -> 1

This throws errors in developer tools console while using ':value:sync="selectedValue"' or with 'v-model="selectedValue"' - `[Vue warn]: Invalid prop: type check failed for prop "value". Expected String, Number, Boolean, Array, got Object`

In my case it makes to impossible to make proper body for request to API.

**Comment by woothu** [comment]
This has been fixed, which version of coreui-vue do you have?

**Comment by miedzwin** [comment]
I'm using version 3.0.0
```
 "dependencies": {
        "@coreui/coreui": "^3.0.0",
        "@coreui/icons": "^1.0.1",
        "@coreui/vue": "^3.0.7",
        "@coreui/vue-chartjs": "^1.0.5"
    }
```

**Comment by woothu** [comment]
I see you have at least 3.0.7 version, please try updating to 3.0.9

**Comment by miedzwin** [comment]
Thank you.
Updating package solve the issue.
Sorry for creating new issue, I just didn't found any information about this bug.

**Comment by sacden** [comment]
> Thank you.
> Updating package solve the issue.
> Sorry for creating new issue, I just didn't found any information about this bug.

sorry, how can i update this theme in my project?
