### ISSUE TITLE
page content shifts on page load

### ISSUE THREAD

**Issue by michalanto** [coreui/coreui-free-vue-admin-template#218]
I'm using the latest version of this project. When I navigate between the pages of the template, sometimes the content shifts while the page loads. Happens inconsistently.

I'm using Chrome on MacOS Mojave.

How to reproduce:
1. Clone coreui-vue from github
2. Open it in the browser.
3. Click Base -> Breadcrumbs in the side menu.
4. Click Colors in the side menu.

![ezgif-6-f73beac1bda2](https://user-images.githubusercontent.com/14348263/79480580-f538d600-8016-11ea-829a-7ab262658ccd.gif)

**Comment by woothu** [comment]
fixed in 3.1.0 version
