### ISSUE TITLE
npm build on AWS fails vs local system

### ISSUE THREAD

**Issue by danyal14** [coreui/coreui-free-vue-admin-template#221]
Hi,

I have almost tried various node versions, locally as well as on aws container build FROM node:10-alpine, when running npm run build gets following error. Locally it works perfectly fine.

We have license for Coreui pro all, I wrote to support there is no answer for last 3 days waiting time.
 
3 packages are looking for funding 

`
> @coreui/coreui-pro-vue-admin-template-starter@2.1.5 build /usr/src/app
--
198 | > vue-cli-service build "--mode" "stage"
199 |  
200 | ·[91minternal/modules/cjs/loader.js:638
201 | throw err;
202 | ^
203 |  
204 | Error: Cannot find module '../package.json'
205 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
206 | at Function.Module._load (internal/modules/cjs/loader.js:562:25)
207 | at Module.require (internal/modules/cjs/loader.js:692:17)
208 | at require (internal/modules/cjs/helpers.js:25:18)
209 | at Object.<anonymous> (/usr/src/app/node_modules/.bin/vue-cli-service:5:25)
210 | at Module._compile (internal/modules/cjs/loader.js:778:30)
211 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
212 | at Module.load (internal/modules/cjs/loader.js:653:32)
213 | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
214 | at Function.Module._load (internal/modules/cjs/loader.js:585:3)
215 | ·[0m·[91mnpm·[0m·[91m ERR! code ELIFECYCLE
216 | ·[0m·[91mnpm ·[0m·[91mERR! errno 1

`

**Comment by woothu** [comment]
Hi!

Sorry for the support waiting time.

The issue from support is not related to this issue. This issue is also not related to our starter project, but to CI environment configuration.

Notice that there are already version 3 available and v2 receive only critical fixes 

Regards

**Comment by xidedix** [comment]
@danyal14 
https://stackoverflow.com/questions/61325987/aws-lambda-layers-error-when-call-api-cannot-find-module

**Comment by xidedix** [comment]
@danyal14 
https://stackoverflow.com/questions/58024446/node-cannot-find-module-package-json-closed
