### ISSUE TITLE
CTable's border doesn't work

### ISSUE THREAD

**Issue by rlabrecque** [coreui/coreui-free-vue-admin-template#224]
https://github.com/coreui/coreui-free-vue-admin-template/blob/9132c2f449f367dc81e0ee6f39c6ec7958f0280a/src/views/base/Table.vue#L12

CTable uses the prop "bordered", but CDataTable uses "border", thus CTable should either set "border" on CDataTable, or preferably it should be updated to use "border" everywhere.

**Comment by woothu** [comment]
fixed in 3.1.0 version
