### ISSUE TITLE
Best way to upgrade coreui-free-vue-admin-template version

### ISSUE THREAD

**Issue by rocchidavide** [coreui/coreui-free-vue-admin-template#228]
What is the best way to update coreui-free-vue-admin-template version? In a production project I have the 3.0.2, I'd like to upgrade to the latest (currently is 3.1.0) but I don't want to risk to brake something... Thank you.

**Comment by woothu** [comment]
The template should be used only as a resource to copy solutions:

The best practice is having the latest template in one folder and keep this folder up to date with the master branch (doesn't modify the template at all), and only copying the fragments of code to your project.
