### ISSUE TITLE
Differences between starter / full project ?

### ISSUE THREAD

**Issue by vpratfr** [coreui/coreui-free-vue-admin-template#23]
Just wondering if having those 2 sub-projects is worth the maintainance hassle.

What is the real difference between them? Would not it be easier and cleaner to have a single CoreUI-Vue project and focus on new features / bug fixes in a single place?

**Comment by woothu** [comment]
Hello! 
Pro version of CoreUI have additional features, so the projects have to be separated.
The issue of maintenance is solved by utilizing coreui-vue library in both libraries.
