### ISSUE TITLE
How do I set a method on CModal Buttons?

### ISSUE THREAD

**Issue by geri777** [coreui/coreui-free-vue-admin-template#233]
I can't find any information on how to bind a function on a modal footer button here:
https://coreui.io/vue/docs/components/modal.html#cmodal-api

An example for using own buttons in the footer slot would also be highly appreciated.
Many thanks for your help

**Comment by zudith** [comment]
you can override the footer like this,

`<template #footer>`
`<CButton @click="...." color="danger">Discard</CButton>`
`<CButton @click="...." color="success">Accept</CButton>`
`</template>`
