### ISSUE TITLE
How to remove # from URL?

### ISSUE THREAD

**Issue by topex-psy** [coreui/coreui-free-vue-admin-template#234]
When I load dashboard it appears in the address bar as http://localhost:8080/#/dashboard
How can we remove that # from URL?

**Comment by xidedix** [comment]
@topex-psy see: 
- https://router.vuejs.org/api/#mode
- https://router.vuejs.org/guide/essentials/history-mode.html

duplicate https://github.com/coreui/coreui-free-vue-admin-template/issues/7
