### ISSUE TITLE
Use dropdown button inside datatable not working as expected

### ISSUE THREAD

**Issue by topex-psy** [coreui/coreui-free-vue-admin-template#235]
the `.dropdown-menu` is truncated inside table the by `.table-responsive`. I know there's `data-boundary="viewport"` attribute to get it work in Botstrap 4, but how to solve it in CoreUI's DataTable?

Here's my current code:
```
<td slot="action" slot-scope="{item}" @click="$event.stopPropagation()" class="d-flex">
  <CDropdown toggler-text="Action" size="sm" color="info">
    <CDropdownItem v-for="action in actions" :key="action.label" @click="actionClick(action, item[idColumn])">
      {{action.label}}
    </CDropdownItem>
  </CDropdown>
</td>
```

![Dropdown menu inside CoreUI datatable not working](https://user-images.githubusercontent.com/14989865/95704620-b4dfab00-0c7b-11eb-926e-16ba15c8a1f3.png)

**Comment by GuilhermeAmado** [comment]
Did you found a solution to this?

**Comment by yauheniivashkevich** [comment]
Any updates?

**Comment by ImAgentW** [comment]
Having same problem

**Comment by ivaancruzz** [comment]
Maybe it's a little late for this. But if anyone else has this problem just add "position-static" in the dropdown component

`<CDropdown className="position-static">`
