### ISSUE TITLE
There is no documentation for new multi-selects anywhere!

### ISSUE THREAD

**Issue by windows8prew** [coreui/coreui-free-vue-admin-template#240]
I bought vue pro version to see examples of [multiselects](https://coreui.io/vue/demo/3.2.2/#/forms/multi-select). But I was given the 3.1.0 version, instead of 3.2.2 (the current version). Wrote to support more than 48 hours ago and did not get a response. Can anyone help with this issue ??

**Comment by xidedix** [comment]
See: https://coreui.io/vue/docs/3.2/components/multi-select.html

**Comment by windows8prew** [comment]
@xidedix Thanks alot
