### ISSUE TITLE
Problem with npm install

### ISSUE THREAD

**Issue by torniker** [coreui/coreui-free-vue-admin-template#245]
so I just download this project and tried to run `npm install`... Here is the output:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @coreui/coreui-free-vue-admin-template@3.1.2
npm ERR! Found: vue@2.6.12
npm ERR! node_modules/vue
npm ERR!   vue@"~2.6.12" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"3.0.5" from @vue/compiler-sfc@3.0.5
npm ERR! node_modules/@vue/compiler-sfc
npm ERR!   peerOptional @vue/compiler-sfc@"^3.0.0-beta.14" from @vue/cli-service@4.5.11
npm ERR!   node_modules/@vue/cli-service
npm ERR!     peer @vue/cli-service@"^3.0.0 || ^4.0.0-0" from @vue/cli-plugin-babel@4.5.11
npm ERR!     node_modules/@vue/cli-plugin-babel
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/someone/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/someone/.npm/_logs/2021-02-10T14_31_05_573Z-debug.log
```

# Additional Info:

OS: macOS Big Sur 11.2.1
node: v15.8.0
npm: 7.5.0

I've search around and found this: [https://stackoverflow.com/a/64872578/413026](https://stackoverflow.com/a/64872578/413026)
Hopefully this will help.

**Comment by okiaba** [comment]
I have the same issue, `npm install --legacy-peer-deps` seems to solve it for me.
see https://github.com/team-innovation/vue-sfc-rollup/issues/70 and https://github.com/vuejs/vue-cli/issues/6270

**Comment by botardo** [comment]
More problems with npm install - same as original question: download, npm install, break

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @coreui/coreui-free-vue-admin-template@4.0.0-rc.0
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.32.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.15
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"~4.5.14" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\darko\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Local\npm-cache\_logs\2021-11-21T20_55_22_932Z-debug.log
