### ISSUE TITLE
@jthieba  Thank you very much.

### ISSUE THREAD

**Issue by john-mbone** [coreui/coreui-free-vue-admin-template#247]
@jthieba  Thank you very much.
I believe I tried it before but I don't know/remember why it didn't work.
Anyway, it works now.

_Originally posted by @shahwan42 in https://github.com/coreui/coreui-free-vue-admin-template/issues/88#issuecomment-394156768_

How did you solve it?

**Comment by shahwan42** [comment]
The previous comment in the same thread solved the issue for me at that time. I no longer use the coreui template and I don't know how it could be solved now.

**Comment by john-mbone** [comment]
Thank you.
