### ISSUE TITLE
Icon list that we can use in SidebarNav

### ISSUE THREAD

**Issue by sandrocantagallo** [coreui/coreui-free-vue-admin-template#252]
**LOCAL ENVIRORMENT**
- Operating system and version (Windows, Win10)
- Browser and version (Chrome)

**ISSUE**

in: src\containers\_nav.js

Can't use for example: 

`icon: 'cil-blind',`

I would like to have a list of usable icons for SideBarNav.

cil-speedometer: works
cil-pencil: works

cil-blind: not works
cil-bar-chart: not works

and so on...

**Comment by masada6** [comment]
Hi,

In scr/main.js a set of icons is made globally available by importing iconsSet from src/assets/icons/icons.js:
https://github.com/coreui/coreui-free-vue-admin-template/blob/9d65013c0f683a70d986040e63e84459a4933d5d/src/main.js#L6

To utilize more icons in _nav.js (or wherever) import/export them in icons.js.

For more information about working with the Icons component i would recommend reading the Icons section in the [CoreUI docs](https://coreui.io/vue/docs/components/icon.html).

**Comment by sandrocantagallo** [comment]
Thanks a lot!
