### ISSUE TITLE
Master zip file not found during composer update

### ISSUE THREAD

**Issue by jle-jware** [coreui/coreui-free-vue-admin-template#262]
Hi  @mrholek , my project was working fine a couple of days ago. Now when I am running composer update I am getting the following error. Now my project is down.

[Composer\Downloader\TransportException]
 The "https://codeload.github.com/coreui/coreui-free-vue-admin-template/zip/master" file could not be downloaded (HTTP/2 404 )

Need urgent help to fix this issue.

TIA

**Comment by mrholek** [comment]
Try to change https://codeload.github.com/coreui/coreui-free-vue-admin-template/zip/master to https://codeload.github.com/coreui/coreui-free-vue-admin-template/zip/v3

**Comment by jle-jware** [comment]
This is on my composer.lock file.

![image](https://user-images.githubusercontent.com/50643973/141663962-c215e170-d13f-4bd1-bc22-001772665225.png)

Do I need to update with this link https://codeload.github.com/coreui/coreui-free-vue-admin-template/zip/v3?

**Comment by jle-jware** [comment]
Hi, @mrholek  Please need a quick solution as the project needs to go live by morning.

TIA
