### ISSUE TITLE
Can you please add a global search bar?

### ISSUE THREAD

**Issue by shoorlyne** [coreui/coreui-free-vue-admin-template#263]
We'd like to have a search bar in the top-level nav bar, so that any time a user wants to search for something, he can use that.

See below for an example:

<img width="1268" alt="Screen Shot 2021-11-21 at 4 49 41 PM" src="https://user-images.githubusercontent.com/20250340/142755773-22d10336-c11e-4e57-a0c1-4daa35f6c17b.png">

**Comment by ahmadjubair33** [comment]
sure
