### ISSUE TITLE
Links doesn't work properly with history: createWebHistory

### ISSUE THREAD

**Issue by sametsafak** [coreui/coreui-free-vue-admin-template#272]
When I switch router mode from hash to web history and try to access any page from sidebar or breadcrumb, app downloads all of the files again and again like opened from scratch. It works like old non single page applications.

But when I put a router link myself like:
`<router-link to="/dashboard">hello</router-link>`
It works normally. Loads only page related files.

- Mac OS Monterey
- Chrome 97.0.4692.99 Arm

**Comment by sametsafak** [comment]
I checked **AppSidebarNav.js** and set `custom` prop to **false** in h function that creates `RouterLink`. 
It solves 2 problems and creates 2 problems.

Solved problems:
1- createWebHistory is working fluidly
2- router.beforeEach was triggered twice before I set 'custom' prop to false. Now it triggers only once.

Created problems:
1- 'custom' prop's definition in node_modules>vue router>RouterLink says:
 _Whether RouterLink should not wrap its content in an `a` tag. Useful when using `v-slot` to create a custom RouterLink_
Therefore now all sidebar `li` tag are wrapped in `a` tag. It seems doesn't affect anything badly but works.
2- breadcrumb and other components that has router-link are working like my first comment. i guess they all have this `custom` property :(

**Comment by zeeforum** [comment]
In AppSidebarNav.js code is look like this:

```
{
	default: (props) => h(
		resolveComponent(item.component),
		{
			active: props.isActive,
			href: props.href,
			onClick: () => props.navigate(),
		},
		{
			default: () => [
			item.icon &&
				h(resolveComponent('CIcon'), {
				customClassName: 'nav-icon',
				name: item.icon,
				}),
			item.name,
			item.badge &&
				h(
				CBadge,
				{
					class: 'ms-auto',
					color: item.badge.color,
				},
				{
					default: () => item.badge.text,
				},
				),
			],
		},
	),
},
```

You can customize the child item using render function h. Here is my code that does the trick:

```
{
	default: (props) => h(
		resolveComponent(item.component),
		{
			active: props.isActive,
		},
		{
			default: () =>  h(
				RouterLink,
				{
					to: props.href,
					class: 'nav-link',
					onClick: () => props.navigate(),
				},
				{
					default: () => [
					item.icon &&
						h(resolveComponent('CIcon'), {
						customClassName: 'nav-icon',
						name: item.icon,
						}),
					item.name,
					item.badge &&
						h(
						CBadge,
						{
							class: 'ms-auto',
							color: item.badge.color,
						},
						{
							default: () => item.badge.text,
						},
						),
					],
				},
			),
		},
	),
},
```

I have removed href and onClick props from the original code. And shifted them into RouterLink render function and href converted to "to" attribute for RouterLink. For css added the class nav-link.

That does the trick.
Hope it helps.

**Comment by sametsafak** [comment]
@zeeforum Yes it helped, thank you!

**Comment by zeeforumcompany** [comment]
> @zeeforum Yes it helped, thank you!

You are welcome!

**Comment by rofequl** [comment]
Links doesn't work properly with history: createWebHistory
The issue not resolved yet.
