### ISSUE TITLE
mobile page is disabled after sidebar hide

### ISSUE THREAD

**Issue by tim1047** [coreui/coreui-free-vue-admin-template#278]
I developed my site using coreui-free-vue-admin-template.
However, mobile page is disabled after sidebar hide (after navItem click).
PC is working well.

How can i solve this problem?

**Comment by tim1047** [comment]
IOS is working well, Android is not working.

**Comment by Christian-Infoguia** [comment]
> I developed my site using coreui-free-vue-admin-template. However, mobile page is disabled after sidebar hide (after navItem click). PC is working well.
> 
> How can i solve this problem?

same issue here, works fine in my desktop but in laptop for some reason don't
