### ISSUE TITLE
Sidebar change color schema doesn't work

### ISSUE THREAD

**Issue by vsirghii** [coreui/coreui-free-vue-admin-template#279]
I have free-vue-admin current v 4.1.0
Running in VS code on Windows 11 using Chrome v 99.0.4844.74 (Official Build) (64-bit)

From docs, https://coreui.io/vue/docs/components/sidebar.html, I can clearly see Sidebar property "color-scheme" with possible values "dark or light". By default it's "dark" and works fine. But if I add "color-scheme='light'" it doesn't change the scheme color. Moreover it throughs erros in the console: "_Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'._" "color-scheme='dark'" will through the same error in the console. Only without specifying "color-scheme"  at all, property errors won't be seeing and the theme will be dark which I'd like to change to light.

Could somebody clarify what property and what values should I use to get Sidebar working **light** scheme???

**Comment by mrholek** [comment]
@vsirghii the light version is available only in PRO version

**Comment by vsirghii** [comment]
Thanks @mrholek, sometime later, somewhere from your docs pictures I've got a clue that this might be about PRO/FREE versions difference. Just an idea: if you had in the component descriptions something like `color-scheme` **(PRO)**, it would eliminate further questions
