### ISSUE TITLE
Replace VueX with Pinia

### ISSUE THREAD

**Issue by leoplaw** [coreui/coreui-free-vue-admin-template#282]
Using VueX for the navigation state management is overkill. Please use Pinia instead.

https://pinia.vuejs.org/

It is officially endorsed by Vue.

**Comment by johandeklerk** [comment]
@leoplaw Wouldn't be possible to leave vuex as is in core.ui and use pinia for custom app code? It's far from ideal but at least you could work with pinia in that way. Unfortunately I really don't have time to hack core.ui code now but when I do I'll update here.
