### ISSUE TITLE
An error about getComputedStyle.

### ISSUE THREAD

**Issue by Emrehrz** [coreui/coreui-free-vue-admin-template#295]
I modified the coreui & vuejs3 free template and recently get some error about:
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. 
Especially I encounter this error when Im shrink the browser window or resize it.

using windows 10 and latest version chrome browser

**Comment by sametsafak** [comment]
I also have this error. It comes from src/components/sidebar/CSidebar:6 isOnMobile function 

Normally, it's not visible but when I logged out and resize the screen, I can see it. 
I guess this error occurs when the main layout changes and the sidebar becomes hidden. Maybe @mrholek can help us.

**Comment by mrholek** [comment]
I tried to reproduce this error but with no success, can you tell me how I can reproduce it?
