### ISSUE TITLE
How are components pulled in?

### ISSUE THREAD

**Issue by lucavallin** [coreui/coreui-free-vue-admin-template#32]
I see this:

```
<script>
export default {
  name: 'ip-uploader',
  data: {
    ips: ''
  },
  methods: {
    upload: (ips) => {
      alert(ips)
    }
  }
}
</script>
```

but I am used to this:
```
Vue.component('symbols-table', {
    data: {
        symbols: []
    },
    created: function(){
        axios.get('symbols.json').then(response => this.symbols = response.data);
    }
});
```

For what I can see in the code, components are never registered like this. Can anyone explain me the flow?

**Comment by mrholek** [comment]
Hi,

There are several ways to define a component in Vue.js, please check this: https://medium.com/js-dojo/7-ways-to-define-a-component-template-in-vuejs-c04e0c72900d.

We use single page components.
