### ISSUE TITLE
add a real link example

### ISSUE THREAD

**Issue by mariusa** [coreui/coreui-free-vue-admin-template#42]
In
https://github.com/mrholek/CoreUI-Vue/blob/master/Vue_Full_Project/src/components/HeaderDropdown.vue

please add a real link example, example
```
<b-dropdown-item><router-link to='/settings'><i class="fa fa-wrench"></i> Settings</router-link></b-dropdown-item>
```
Not sure if this is the best. Styling needs fixing, as it shows an underline when hovering over the menu item (regular anchor tag styling, as it generates a link)

**Comment by woothu** [comment]
This component is deprecated and will be removed in next version.
