### ISSUE TITLE
Include bootstrap-vue.css after bootstrap.css

### ISSUE THREAD

**Issue by donalmurtagh** [coreui/coreui-free-vue-admin-template#44]
According to the [bootstrap-vue docs](https://bootstrap-vue.js.org/docs)  `bootstrap-vue.css` should be included after `bootstrap.css`.

However, in `App.vue`, they are included in the opposite order (`bootstrap.css` is included in `./scss/style`)

```
<style>
  /* Import Font Awesome Icons Set */
  $fa-font-path: '~font-awesome/fonts/';
  @import '~font-awesome/css/font-awesome.min.css';
  /* Import Simple Line Icons Set */
  $simple-line-font-path: '~simple-line-icons/fonts/';
  @import '~simple-line-icons/css/simple-line-icons.css';
  /* Import Bootstrap Vue Styles */
  @import '~bootstrap-vue/dist/bootstrap-vue.css';
</style>
<style lang="scss">
  // Import Main styles for this application
  @import './scss/style';
</style>
```

**Comment by woothu** [comment]
Hi! Thank you for your report!

Although you are right with this suggestion, this is not the pure bootstrap that is included after bootstrap-vue css, but bootstrap based coreui library. There might be customizations that are broken by bootstrap-vue styles.
