### ISSUE TITLE
Full calendar

### ISSUE THREAD

**Issue by vgraveto** [coreui/coreui-free-vue-admin-template#47]
When will it be available a full calendar in Vue version.
When browsing the site I payed for the pro version because the list of plug-in include several choices. one was the full calendar. No information was there advising that the different flavors had different components. Now I discovered that on Vue version lots of them are missing.
This is not fair.

**Comment by rolitter** [comment]
The pro version needs to be purchased. You can choose other plugins,E.g [vue-datepicker](https://github.com/hilongjw/vue-datepicker)

**Comment by mrholek** [comment]
Full calendar is great, but there is one problem, it requires jQuery. We're not going to use jQuery in Vue version, that's why FC is not available in this version.

At this moment we're working on version 2.0.0, but we will try to add datepicker ASAP

**Comment by xidedix** [comment]
for simple datepicker you can use form input like this:
https://github.com/mrholek/coreui-free-vue-admin-template/blob/62c6b92ec45c8c01a144e7ed028e61806d9ce39b/Vue_Full_Project/src/views/base/Forms.vue#L120-L125

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive or answered above. Please comment and/or reopen if you feel the issue has not been resolved.
