### ISSUE TITLE
Implement on NuxtJS

### ISSUE THREAD

**Issue by muhibbudins** [coreui/coreui-free-vue-admin-template#55]
Hi guys,

Thank you very much for awesome template from CoreUI. And now i try to implement this project on NuxtJS.

You can see my project on this link [NuxtJS + Core UI](https://github.com/muhibbudins/nuxt-coreui)

Thank you 😄

**Comment by woothu** [comment]
Hi!
Thank you very much for your work! 

CoreUI team.
