### ISSUE TITLE
Request - Can we get a datetimepicker component? 

### ISSUE THREAD

**Issue by bgarrison25** [coreui/coreui-free-vue-admin-template#59]
This could be something for every coreui project. DateTimePicker is something i use in 90% of my projects so it would be a real help if I didn't have to pigeon hole some square code into this round project ;).

**Comment by xidedix** [comment]
for simple datepicker you can use form input like this:

https://github.com/mrholek/coreui-free-vue-admin-template/blob/62c6b92ec45c8c01a144e7ed028e61806d9ce39b/Vue_Full_Project/src/views/base/Forms.vue#L120-L125
