### ISSUE TITLE
Integrating the CoreUI Pro

### ISSUE THREAD

**Issue by charitablehumans** [coreui/coreui-free-vue-admin-template#67]
How can I integrate the professional paid version of CoreUI with this?

**Comment by charitablehumans** [comment]
Any help on this?

**Comment by mrholek** [comment]
Hi, 

Why you want to integrate pro version with free version?

Pro version extends free version.

Regards
Lukasz

**Comment by charitablehumans** [comment]
Because I'm trying to get it to work with Laravel and can't get it working, nor find instructions on how to do it. I've tried everything, but just keep getting errors.

**Comment by begnini** [comment]
This version is more updated. The pro version (1.8.14) uses bootstrap-vue 1.4, and this use 2.0.0-rc. I don't know if there many modifications, but I starting one project now and want to start with the last libs available. I don't know the work to migrate after.

**Comment by charitablehumans** [comment]
Does anyone have instructions on integrating this (Pro version) with Laravel?

**Comment by charitablehumans** [comment]
I'm regretting purchasing the CoreUI Pro, support is nonexistent.

**Comment by iamgenesisivan** [comment]
@charitablehumans Do you still need support for CORE UI Pro Integration to laravel fresh Project?
message me.

**Comment by eduditurbide** [comment]
@iamgenesisivan please, can you help me to integrate coreUi Pro to laravel ? please

**Comment by iamgenesisivan** [comment]
@eduditurbide yes sir. you can contact me on aquino.igeneesis@gmail.com

**Comment by hatimox** [comment]
hello @iamgenesisivan , @eduditurbide i have the same issue can you help me to integrate the pro version with fresh laravel project?

**Comment by iamgenesisivan** [comment]
Hello @hatimox, Yes I can help you, just inbox me. aquino.igenesis@gmail.com

**Comment by woothu** [comment]
Hello!

We would recommend to have separate laravel and coreui projects and use laravel only as a RESTful API, because in SPA frontend approach you can't really utilize laravel blade templates.

This solution also brings more flexibility and is making frontend of the app reusable for other backend solutions.
