### ISSUE TITLE
Stand alone page - may even a landing page

### ISSUE THREAD

**Issue by sbasi5576** [coreui/coreui-free-vue-admin-template#71]
It seems like pages such as login and signup have to be nested within the page/.  Is there a way to have them as stand alone?   For example, can I do:
  
  {
          path: 'login',
          name: 'Login',
          component: Login
        },
        {
          path: 'register',
          name: 'Register',
          component: Register
        }

Instead of - 

{
      path: '/pages',
      redirect: '/pages/404',
      name: 'Pages',
      component: {
        render (c) { return c('router-view') }
      },
      children: [
        {
          path: '404',
          name: 'Page404',
          component: Page404
        },
        {
          path: '500',
          name: 'Page500',
          component: Page500
        },
        {
          path: 'login',
          name: 'Login',
          component: Login
        },
        {
          path: 'register',
          name: 'Register',
          component: Register
        }
      ]
    }

**Comment by woothu** [comment]
This is only template example, you are free to change it in any way, this solution is fully possible.
