### ISSUE TITLE
Upgrade to Font Awesome 5

### ISSUE THREAD

**Issue by akhchan99** [coreui/coreui-free-vue-admin-template#73]
Any plan to upgrade to Font Awesome 5?

**Comment by xidedix** [comment]
to install & upgrade from 4 to 5 see:
https://fontawesome.com/how-to-use/js-component-packages
https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by mariusa** [comment]
How about removing font-awesome from package.json and let us use what icon font we want? eg https://themify.me/themify-icons

If one needs font awesome, one can easily add it to index.html as any other CSS. Feel free to add it there by default, but not in package.json, so we can have a smaller build.

themify-icons also work in ```_nav.js```, use ```icon: 'ti ti-id-badge'```
