### ISSUE TITLE
Promise object problem on IE

### ISSUE THREAD

**Issue by spartanonapoletano** [coreui/coreui-free-vue-admin-template#76]
Hi 
I try to use CoreUI-Vue on IE, unfortunatly theme doesn't work fine. In web browser console, there are problem about Promise object. I red some articles about Promise issues problem on IE.
I understand that I can't use Promise on IE and so I can't use COre UI - Vue on IE.
Could you help me?!

**Comment by xidedix** [comment]
hi @spartanonapoletano 
- which version of IE?
- what about Promise polyfill? have you tried this? does it help? 
ex:
https://www.npmjs.com/package/promise-polyfill
https://github.com/zloirock/core-js

**Comment by spartanonapoletano** [comment]
Hi 
IE 10 & 11

Browser can't use Promise object

**Comment by xidedix** [comment]
hi @spartanonapoletano 
cannot reproduce the issue with `v1.0.11` of CoreUI
which version of CoreUI fails with IE?

IE does not support Promises by default, but polyfills should help

**Comment by xidedix** [comment]
@spartanonapoletano 

here we go:
1. install `core-js` library in your project directory, for example:
````bash
cd Vue_Full_Project
npm i core-js
````
2. modify file `Vue_Full_Project\src\main.js` 
before `import Vue from 'vue'` add following import as the first line 
````javascript
import 'core-js/es6/promise'
````
3. run it
````bash
npm start
````

I hope this helps

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive or answered above. Please comment and/or reopen if you feel the issue has not been resolved.
