### ISSUE TITLE
Error in npm run dev.

### ISSUE THREAD

**Issue by hifall** [coreui/coreui-free-vue-admin-template#80]
When trying to run: npm run dev, I got:

> @coreui/vue@1.0.12 dev /Applications/MAMP/htdocs/my-project
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 94% asset optimization                                                       c         
 ERROR  Failed to compile with 2 errors                                 11:49:03

These dependencies were not found:

* -!../node_modules/css-loader/index.js?{"sourceMap":true}!./bootstrap-vue/dist/bootstrap-vue.css in ./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"optionsId":"0","vue":true,"scoped":false,"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=1!./src/App.vue
* -!../node_modules/css-loader/index.js?{"sourceMap":true}!./flag-icon-css/css/flag-icon.min.css in ./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"optionsId":"0","vue":true,"scoped":false,"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=1!./src/App.vue

To install them, you can run: npm install --save -!../node_modules/css-loader/index.js?{"sourceMap":true}!./bootstrap-vue/dist/bootstrap-vue.css -!../node_modules/css-loader/index.js?{"sourceMap":true}!./flag-icon-css/css/flag-icon.min.css

I then tried to install the dependencies as suggested in the messages, but it did not succeed.

**Comment by xidedix** [comment]
- what's your version of node and npm ?

sometimes things go wrong with npm install
try:
- remove `node_modules` directory
- remove `package-lock.json` file
- then `npm install` from the scratch

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive or answered above. Please comment and/or reopen if you feel the issue has not been resolved.
