### ISSUE TITLE
Table's responsiveness bug.

### ISSUE THREAD

**Issue by hifall** [coreui/coreui-free-vue-admin-template#85]
Navigate to: https://coreui.io/v1/demo/pro/Vue_Demo/#/tables, then scroll to the bottom of the page, there is a 'Combined All Table' there. Now reduce the width of the window, and when it's about 450px, you will notice some UI issue: there is a gap between the right border of the table and the right borders of the last cells on each row.

**Comment by woothu** [comment]
Issue solved in new version. https://coreui.io/vue/demo/#/tables/tables
