### ISSUE TITLE
Make badges in the sidebar menu dynamic

### ISSUE THREAD

**Issue by miki996** [coreui/coreui-free-vue-admin-template#86]
Hi, 

I wanted to make the badges in the sidebar menu dynamic and to show an exclamation badge if some of the fields in the database empty using a fetch request. 

But it seems like when i am doing the fetch request from the `_nav.js` file the links from the file are exported before the fetch request is over.

I wasn't able to figure out any other way of doing this but if you do please let me know.

Sample code here: https://jsfiddle.net/w97v0eoc/

**Comment by xidedix** [comment]
Hi @miki996 
How did you manage to solve this problem?
