### ISSUE TITLE
how to use font awesome icons in navbar links?

### ISSUE THREAD

**Issue by aloay** [coreui/coreui-free-vue-admin-template#88]
in `_nav.js`: what value should be put for `icon` in order to use font awesome instead of coreui built-ins?

**Comment by jthieba** [comment]
```
{
      name: 'Books',
      url: '/library/books',
      icon: 'fa fa-book',
},
```

**Comment by aloay** [comment]
@jthieba  Thank you very much.
I believe I tried it before but I don't know/remember why it didn't work.
Anyway, it works now.

**Comment by blcksheep80** [comment]
> simply put 'fa fa-iconName'
> 
> ```
> {
>       name: 'Books',
>       url: '/library/books',
>       icon: 'fa fa-book',
> },
> ```

This doesn't seem to work anymore :( Or do I need to be using a specific version of either Font Awesome or CoreUI?

**Comment by woothu** [comment]
Yes, API have changed in version 3 (available in docs). Now for font icon use 'fontIcon' key instead.

**Comment by lcharette** [comment]
As I understand `fontIcon` key requires the FA library to be loaded as CSS, as anyone got the FA icon to be displayed in the sidebar using the SVG/JS method, per [the recommended FA installation and usage](https://github.com/FortAwesome/vue-fontawesome#installation)?

**Comment by john-mbone** [comment]
Hello, i am still unable to add fontawesome icon even after using fontIcon in navigation
