### ISSUE TITLE
". . .Consider marking event handler as 'passive' to make the page more responsive"

### ISSUE THREAD

**Issue by humblecoder** [coreui/coreui-free-vue-admin-template#9]
Receiving the following error:
```
Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive
```
From a cursory glance, I'm not sure which items specifically are responsible, but the issue may be related to the following issue report:

https://github.com/leongersen/noUiSlider/issues/785

**Comment by woothu** [comment]
Is this still an issue?

**Comment by felipelc454** [comment]
hello i'm having the same problem, i'm using Coreui Angular
