### ISSUE TITLE
how to change sidebar 

### ISSUE THREAD

**Issue by rockyshukla** [coreui/coreui-free-vue-admin-template#94]
hello folks,

 your  vue template is really awesome but I want to know is it possible to give sidebar nav hover effect on desktop vue if yes can you provide location which is required to change

**Comment by woothu** [comment]
You can modify sidebar in src/containers/DefaultContainer.vue 
There, in SidebarNav component you can pass your css class which will be aplied to html nav component

```html
<SidebarNav :navItems="nav" class="yourClass"></SidebarNav>
```
You can also get SidebarNav component from coreui-vue library and modify it.

**Comment by woothu** [comment]
Add a class to the SidebarNav as I mentioned before and inspect sidebar element, you will notice that class is attached to html element. Then you can review sidebar html tree and operate on the element class is attached to and its descendants (https://www.w3schools.com/css/css_combinators.asp)

**Comment by eddivalen** [comment]
Hey @woothu, thank you! I know what you mean, but I need to modify de Sidebar Nav to show the sidebar items depending on role authenticated, so I need to add a v-if condition to every option

**Comment by woothu** [comment]
For now, I would suggest adding property such as "authentication" to every item you need to authenticate in _nav.js object and compare user rights to that prop. Then you can create computed property in DefaultContainer.vue which will filter your _nav.js object.

Example - excluding dashboard from sidebar: 
```javascript
  data () {
    return {
      nav: nav.items
    }
  },
  computed: {
    computedNav () {
      return this.nav.filter((item) => item.name !== 'Dashboard')
    }
  }
```

```html
<SidebarNav :navItems="computedNav "/>
```

**Comment by eddivalen** [comment]
Hey again! @woothu **Thanks a bunch!!!** This works perfect

**Comment by marsanaemi** [comment]
Hello!
i want to move sidebar from left to  right in page but i dont know what i have to change

**Comment by mochamadakbar** [comment]
@woothu can i use permission in _nav.js before add to sidebar component ?. example :

in _nav.js
```
export default {
  items: [
    {
      name: 'Dashboard',
      url: '/dashboard',
      icon: 'icon-speedometer',
      permission: 'dashboard'
    },
  ]
}
```

and i want to add v-if in SideBarNav.vue like

```
<template v-if="item.title && $can(item.permission)">
  <SidebarNavTitle :key="index" :name="item.name" :classes="item.class" :wrapper="item.wrapper"/>
</template>
```

> $can() is function i created when user login check user has permission if use dont have item in sidebar not showing

but that doesn't work, please help

**Comment by woothu** [comment]
Hi!

First od all I strongly recommend to use version 3 of template and library.

If you want such behavior you have two options: 
1. Render nav.js object in computed properties depending on permissions.
2. Use normal components tree with conditional statements.

**Comment by mochamadakbar** [comment]
@woothu thank you for quickly replying,

Is it like this ?

```
  computed: {
    name () {
      return this.$route.name
    },
    list () {
      return this.$route.matched.filter((route) => route.name || route.meta.label )
    }
  },
```

but I still don't understand where I should enter the $can() function. Is it in the list function? or where?

this is my first time using vue js.

**Comment by woothu** [comment]
So please get familiar with the framework ;)

You can create another computed property where you filter items by $can function
